import { ENGINE_NAMES } from './pipeline.js';

/**
 * Machine-readable description of every vNext capability (served at GET /api/sfre/capabilities and rendered by the UI).
 * It is the single place where inputs, assumptions, hand-offs and honest limitations of the new engines are stated;
 * a test asserts that every pipeline engine added in vNext has an entry.
 */
const COMMON_LIMITS = ['UNCALIBRATED scenario model: outputs are conditional on the stated assumptions, not forecasts', 'missing data is reported as UNOBSERVED and never read as zero; totals are lower bounds where flagged', 'synthetic test success is not predictive validity'];
export const CAPABILITIES = Object.freeze([
  { engine: 'crossSector', models: ['M60.cross_sector'], title: 'Cross-sector stress', summary: 'Banks, funds, insurers, corporates, sovereign, households, foreign investors on one exposure network; shocks propagate in default waves (Rogers-Veraart clearing).', needs: ['system.entities', 'system.exposures'], scenario: ['priceShocks', 'externalShocks', 'sectorShocks'], assumptions: ['limited liability', 'pro-rata payment', 'bankruptcy-cost parameters alpha/beta (default 1 = none)'], produces: ['default waves', 'sector transmission matrix', 'value-conservation identity'], limitations: COMMON_LIMITS },
  { engine: 'fxContagion', models: ['M61.fx_contagion'], title: 'FX & cross-border contagion', summary: 'Capital flow -> FX liquidity -> exchange-rate shock -> FX debt/balance-sheet effect -> credit/liquidity losses -> contagion.', needs: ['system.fx', 'FOREIGN_INVESTOR entities', 'FCY exposures'], scenario: ['fx.capitalFlow', 'fx.depreciation', 'fx.rolloverRates'], assumptions: ['sqrt market impact for the exchange rate (caller-supplied Y, sigma, ADV)', 'hedges fully effective', 'exogenous + endogenous depreciation additive'], produces: ['depreciation', 'entity FCY gaps', 'revalued FCY exposures', 'domestic asset sales'], limitations: COMMON_LIMITS },
  { engine: 'sovNexus', models: ['M62.sovereign_bank_corporate'], title: 'Sovereign-bank-corporate nexus', summary: 'Spread shock -> bond MTM -> bank capital -> funding & credit conditions -> corporate PD/loss -> sovereign backstop -> spread (fixed point).', needs: ['system.sovereign', 'bond asset with duration', 'entity.bank'], scenario: ['sovereign.spreadShockBps'], assumptions: ['duration-convexity pricing', 'reduced-form pass-through, PD, crunch and spread sensitivities (null = channel excluded, not zero)', 'HTM losses unrecognised in accounting capital'], produces: ['loop trace', 'spread amplification', 'bank capital shortfalls', 'pre-applied bank losses from other engines'], limitations: [...COMMON_LIMITS, 'non-convergence is reported (MODEL_UNCERTAIN), not hidden'] },
  { engine: 'collateral', models: ['M63.margin_collateral'], title: 'Margin, repo & collateral', summary: 'Initial/variation margin, repo haircuts, eligibility & substitution, margin-call spiral with collateral fire sales, counterparty exposure and wrong-way risk.', needs: ['system.collateral', 'asset sigma'], scenario: ['collateral.priceShocks', 'collateral.volMultiplier', 'collateral.haircutAdd'], assumptions: ['parametric IM z*sigma*sqrt(MPOR)', 'no hedge offset unless a correlation mode is supplied', 'IM assumed posted at model level when unobserved', 'Gaussian one-factor wrong-way dependence'], produces: ['calls by entity', 'sales', 'IM/posted collateral', 'EPE, independent vs wrong-way EL'], limitations: COMMON_LIMITS },
  { engine: 'ccp', models: ['M64.ccp_default_waterfall'], title: 'CCP default waterfall & concentration', summary: 'Defaulter IM -> defaulter DF -> skin-in-the-game -> survivor DF -> assessments, survivor-default propagation, cover-2 test.', needs: ['system.ccps'], scenario: ['ccp.priceShocks', 'ccp.defaulters'], assumptions: ['close-out cost = |position| x price impact', 'member capital observed (null = survivor default not assessable)'], produces: ['layer usage', 'member charges', 'cover-2 ratio', 'IM concentration'], limitations: COMMON_LIMITS },
  { engine: 'privateCredit', models: ['M65.private_credit'], title: 'Private credit / shadow banking', summary: 'Sponsor-clustered default model, leverage covenants, liquidity mismatch and gating, bank/insurer transmission.', needs: ['system.privateCredit', 'PRIVATE_CREDIT entities with loan books'], scenario: ['privateCredit.stressFactor', 'redemptionFractions', 'liquidationDiscount'], assumptions: ['two-level Vasicek factor model with caller-supplied correlations', 'forced loan sales at a discount'], produces: ['stressed loss (analytic + seeded Monte Carlo)', 'covenant & gating outcome', 'borrower/sponsor HHI'], limitations: [...COMMON_LIMITS, 'private-credit PD/LGD are rarely observed: expect UNOBSERVED flags'] },
  { engine: 'aiCrowding', models: ['M66.ai_crowding'], title: 'AI crowding / algorithmic herding', summary: 'Shared signals/models/data -> correlated positioning -> simultaneous orders -> liquidity consumption -> impact -> stop-loss cascade.', needs: ['system.crowding', 'impact model'], scenario: ['crowding.signalShocks', 'crowding.responseScale'], assumptions: ['linear response of target exposure to signal composite', 'independent-flow baseline sqrt(sum Q^2)'], produces: ['effective independent strategies', 'herding ratio', 'cascade multiplier'], limitations: [...COMMON_LIMITS, 'does not show that any real participants share these signals'] },
  { engine: 'opContagion', models: ['M67.operational_contagion'], title: 'Cyber & operational contagion', summary: 'Dependency graph outage -> payment/settlement disruption -> liquidity & margin shortfall. Consequences of a GIVEN scenario only.', needs: ['system.opDeps'], scenario: ['opDeps.outages'], assumptions: ['independent multiplicative availability', 'unobserved substitution = no substitution (stress upper side)'], produces: ['node unavailability', 'failed flows', 'liquidity gaps', 'single points of failure'], limitations: ['never estimates or accepts attack/hack probabilities (rejected loudly)', ...COMMON_LIMITS] },
  { engine: 'climate', models: ['M68.climate_nature'], title: 'Climate & nature stress', summary: 'Transition, physical and nature-dependency shocks into valuation, PD, insurer losses and systemic risk.', needs: ['system.climate'], scenario: ['climate.transition', 'climate.physical', 'climate.nature'], assumptions: ['EBITDA drop = (cost + revenue loss)/margin, capped', 'constant-multiple valuation pass-through', 'probit PD shift'], produces: ['asset haircuts', 'PD shifts', 'insured losses', 'entity effects'], limitations: COMMON_LIMITS },
  { engine: 'digitalAssets', models: ['M69.digital_assets'], title: 'Digital assets', summary: 'Stablecoin run (sequential service), DeFi liquidation cascades on constant-product AMMs, oracle/bridge dependency, liquidity fragmentation.', needs: ['system.digital', 'STABLECOIN/DEFI entities'], scenario: ['digital.stablecoinRedemptions', 'poolShocks', 'bridgeFailures', 'oracleDeviation', 'fragmentationSell'], assumptions: ['AMM mechanics exact; run size, oracle deviation, bridge loss are scenario inputs'], produces: ['peg price of remaining holders', 'bad debt', 'liquidations', 'execution shortfall from fragmentation'], limitations: COMMON_LIMITS },
  { engine: 'surveillance', models: ['M70.spoofing', 'M70.layering', 'M70.wash_trading', 'M70.marking_close', 'M70.order_book_anomaly', 'M70.cross_venue', 'M70.coordinated_trading', 'M70.surveillance_summary'], title: 'Market Surveillance 2.0', summary: 'Seven point-in-time pattern detectors over message streams; Poisson/hypergeometric/permutation tests with Bonferroni control against a strictly earlier reference window.', needs: ['surveillance.events', 'surveillance.referenceEvents', 'surveillance.asOf'], scenario: [], assumptions: ['pseudonymous participant keys only (identity fields rejected)', 'thresholds UNCALIBRATED'], produces: ['pattern findings with salted-hash participant keys', 'corroboration references to M50/M51/M52/M20'], limitations: ['pattern similarity only; never an allegation; intent cannot be inferred', 'NO_SIGNAL is not evidence of compliance'] },
  { engine: 'systemTwin', models: ['M71.system_twin'], title: 'Financial System Digital Twin', summary: 'All engines on one state: SHOCK -> BALANCE-SHEET -> FUNDING/LIQUIDITY -> MARGIN/COLLATERAL -> FORCED ACTION -> MARKET IMPACT -> NETWORK CONTAGION -> SECOND ROUND -> STATE(t+n). One aggregate market impact per asset per round; exact value-conservation ledger.', needs: ['system (all sections used)', 'optional fundSystem (existing M10 cascade)'], scenario: ['any engine scenario key above; a module runs only if both its system section and scenario key exist'], assumptions: ['sales at start-of-round marks', 'fund-cascade effect composed multiplicatively', 'crowding buy-side flows ignored', 'operational margin failures reported not propagated'], produces: ['stage table', 'trajectory', 'channel ledger + reconciliation', 'dataflow'], limitations: COMMON_LIMITS },
]);

export const capabilityGaps = () => CAPABILITIES.map((c) => c.engine).filter((e) => !ENGINE_NAMES.includes(e));
export function describeCapabilities(registryStates = {}) {
  return CAPABILITIES.map((c) => ({ ...c, models: c.models.map((m) => ({ model_id: m, state: registryStates[`${m}@1.0.0`] ?? 'UNREGISTERED', production: registryStates[`${m}@1.0.0`] === 'APPROVED' })) }));
}
